// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Archivos
{
    public int IdArchivo { get; set; }

    public int IdArchivoTipo { get; set; }

    public string NombreOriginal { get; set; }

    public string RutaRelativa { get; set; }

    public DateTime FechaAlta { get; set; }

    public virtual ICollection<Forms_Respuestas_Archivos> Forms_Respuestas_Archivos { get; set; } = new List<Forms_Respuestas_Archivos>();

    public virtual Archivos_Tipos IdArchivoTipoNavigation { get; set; }
}