// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Archivos_Tipos
{
    public int IdArchivoTipo { get; set; }

    public string Descripcion { get; set; }

    public string Extension { get; set; }

    public string MimeType { get; set; }

    public virtual ICollection<Archivos> Archivos { get; set; } = new List<Archivos>();
}