// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class CatalogosSAT
{
    public int IdCatalogoSAT { get; set; }

    public string Catalogo { get; set; }

    public int Indice { get; set; }

    public string Clave { get; set; }

    public string Descripcion { get; set; }

    public int? ClaveInterna { get; set; }

    public bool Habilitado { get; set; }

    public string SubCatalogo { get; set; }
}