// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Contactos_Funciones
{
    public int IdContactoFuncion { get; set; }

    public string AliasFuncion { get; set; }

    public string Funcion { get; set; }

    public int IdUsuarioAlta { get; set; }

    public DateTime FechaAlta { get; set; }

    public int? IdUsuarioModifica { get; set; }

    public DateTime? FechaModifica { get; set; }

    public int? IdUsuarioElimina { get; set; }

    public DateTime? FechaElimina { get; set; }

    public virtual ICollection<Entidades_Contactos_Funciones> Entidades_Contactos_Funciones { get; set; } = new List<Entidades_Contactos_Funciones>();
}