// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Domicilios_Estados
{
    public int ID_Domicilio_Estado { get; set; }

    public string c_Estado { get; set; }

    public string c_Pais { get; set; }

    public string Descripcion { get; set; }
}