// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Domicilios_Colonias
{
    public int ID_Domicilio_Colonia { get; set; }

    public string c_Colonia { get; set; }

    public string Codigo_Postal { get; set; }

    public string Descripcion { get; set; }
}