// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Domicilios_CP
{
    public int ID_Domicilio_CP { get; set; }

    public string Codigo_Postal { get; set; }

    public string c_Estado { get; set; }

    public string c_Municipio { get; set; }
}