// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Domicilios
{
    public int ID_Domicilio { get; set; }

    public bool Es_Facturacion { get; set; }

    public string Descripcion { get; set; }

    public string Calle { get; set; }

    public string Numero_Exterior { get; set; }

    public string Numero_Interior { get; set; }

    public string Codigo_Postal { get; set; }

    public string c_Pais { get; set; }

    public string c_Estado { get; set; }

    public string c_Municipio { get; set; }

    public string c_Colonia { get; set; }

    public string Entre_Calle1 { get; set; }

    public string Entre_Calle2 { get; set; }

    public DateTime Fecha_Alta { get; set; }

    public int Id_Usuario_Alta { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public int? Id_Usuario_Modificacion { get; set; }
}