// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Entidades_Contactos
{
    public int IdEntidadContacto { get; set; }

    public int IdEntidad { get; set; }

    public int IdUsuario { get; set; }

    public string Puesto { get; set; }

    public virtual ICollection<Entidades_Contactos_Funciones> Entidades_Contactos_Funciones { get; set; } = new List<Entidades_Contactos_Funciones>();

    public virtual Entidades IdEntidadNavigation { get; set; }

    public virtual Usuarios IdUsuarioNavigation { get; set; }
}