// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Entidades_Contactos_Funciones
{
    public int IdEntidadContactoFuncion { get; set; }

    public int IdEntidadContacto { get; set; }

    public int IdContactoFuncion { get; set; }

    public virtual Contactos_Funciones IdContactoFuncionNavigation { get; set; }

    public virtual Entidades_Contactos IdEntidadContactoNavigation { get; set; }
}