// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Entidades_Tipos
{
    public int Id_Entidad_Tipo { get; set; }

    public string Entidad_Tipo { get; set; }
}