// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Entidades
{
    public int IdEntidad { get; set; }

    public int? IdExterno { get; set; }

    public Guid UUID_Entidad { get; set; }

    public string Folio { get; set; }

    public string Rfc { get; set; }

    public string RazonSocial { get; set; }

    public string NombreComercial { get; set; }

    public int IdTipoEntidad { get; set; }

    public int? IdTipoRegimenFiscal { get; set; }

    public int IdTipoPersonaSat { get; set; }

    public int? IdEntidadPadre { get; set; }

    public string Email { get; set; }

    public string Web { get; set; }

    public bool Credito { get; set; }

    public decimal LimiteCreditoMXN { get; set; }

    public decimal LimiteCreditoUSD { get; set; }

    public int DiasCredito { get; set; }

    public int? DiasGracia { get; set; }

    public decimal SaldoMXN { get; set; }

    public decimal SaldoUSD { get; set; }

    public string CuentaContable { get; set; }

    public int? IdFormaPago { get; set; }

    public bool Activo { get; set; }

    public int IdUsuarioAlta { get; set; }

    public DateTime FechaAlta { get; set; }

    public int? IdUsuarioModifica { get; set; }

    public DateTime? FechaModifica { get; set; }

    public int? IdUsuarioElimina { get; set; }

    public DateTime? FechaElimina { get; set; }

    public virtual ICollection<Entidades_Contactos> Entidades_Contactos { get; set; } = new List<Entidades_Contactos>();
}