// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Forms_Respuestas_Archivos
{
    public int IdFormRespuestaArchivo { get; set; }

    public int IdFormRespuesta { get; set; }

    public int IdArchivo { get; set; }

    public virtual Archivos IdArchivoNavigation { get; set; }

    public virtual Forms_Respuestas IdFormRespuestaNavigation { get; set; }
}