// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Formularios
{
    public int IdFormulario { get; set; }

    public string ComponentNamespace { get; set; }

    public string ComponentTypeName { get; set; }

    public int IdModulo { get; set; }

    public virtual Modulos IdModuloNavigation { get; set; }

    public virtual ICollection<Menus> Menus { get; set; } = new List<Menus>();

    public virtual ICollection<Permisos> Permisos { get; set; } = new List<Permisos>();
}