// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Forms
{
    public int IdForm { get; set; }

    public string Descripcion { get; set; }

    public string Alias { get; set; }

    public string Titulo { get; set; }

    public string MensajeInicio { get; set; }

    public string MensajeRespuesta { get; set; }

    public int IdFormTemplate { get; set; }

    public string UrlImagen { get; set; }

    public DateTime FechaDesde { get; set; }

    public DateTime? FechaHasta { get; set; }

    public bool EnviarCorreo { get; set; }

    public string Correos { get; set; }

    public string AsuntoCorreo { get; set; }

    public string CuerpoCorreo { get; set; }

    public int IdUsuarioAlta { get; set; }

    public DateTime FechaAlta { get; set; }

    public virtual ICollection<Forms_Respuestas> Forms_Respuestas { get; set; } = new List<Forms_Respuestas>();

    public virtual Forms_Templates IdFormTemplateNavigation { get; set; }
}