// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Forms_Templates
{
    public int IdFormTemplate { get; set; }

    public string Content { get; set; }

    public virtual ICollection<Forms> Forms { get; set; } = new List<Forms>();
}