// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Forms_Respuestas
{
    public int IdFormRespuesta { get; set; }

    public string Folio { get; set; }

    public int IdForm { get; set; }

    public string Respuesta { get; set; }

    public string DireccionIP { get; set; }

    public DateTime FechaAlta { get; set; }

    public virtual ICollection<Forms_Respuestas_Archivos> Forms_Respuestas_Archivos { get; set; } = new List<Forms_Respuestas_Archivos>();

    public virtual Forms IdFormNavigation { get; set; }
}