// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Menus
{
    public int IdMenu { get; set; }

    public string Nombre { get; set; }

    public string NombreEN { get; set; }

    public string Descripcion { get; set; }

    public int Nivel { get; set; }

    public string IconoText { get; set; }

    public string IconoUnicode { get; set; }

    public string IconoCss { get; set; }

    public string RutaPagina { get; set; }

    public int? IdFormulario { get; set; }

    public int? IdMenuPadre { get; set; }

    public bool? Expandido { get; set; }

    public bool Repetir { get; set; }

    public bool Habilitado { get; set; }

    public virtual Formularios IdFormularioNavigation { get; set; }

    public virtual ICollection<Usuarios_Menus> Usuarios_Menus { get; set; } = new List<Usuarios_Menus>();
}