// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Modulos
{
    public int IdModulo { get; set; }

    public string Modulo { get; set; }

    public string EspacioNombre { get; set; }

    public virtual ICollection<Formularios> Formularios { get; set; } = new List<Formularios>();
}