// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Parametros
{
    public int IdParametro { get; set; }

    public int? IdParametroPadre { get; set; }

    public string Alias { get; set; }

    public string Nombre { get; set; }

    public string NombreEN { get; set; }

    public string Descripcion { get; set; }

    public string DescripcionEN { get; set; }

    public int Secuencia { get; set; }

    public bool TieneValores { get; set; }

    public string Valor1 { get; set; }

    public string Valor2 { get; set; }

    public bool Habilitado { get; set; }
}