// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Permisos
{
    public int IdPermiso { get; set; }

    public string Alias { get; set; }

    public string Descripcion { get; set; }

    public string DescripcionEN { get; set; }

    public int? IdFormulario { get; set; }

    public string Endpoint { get; set; }

    public string WebMethod { get; set; }

    public bool IsRole { get; set; }

    public virtual Formularios IdFormularioNavigation { get; set; }

    public virtual ICollection<Usuarios_Permisos> Usuarios_Permisos { get; set; } = new List<Usuarios_Permisos>();
}