// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Personas
{
    public int IdPersona { get; set; }

    public string Nombres { get; set; }

    public string PrimerApellido { get; set; }

    public string SegundoApellido { get; set; }

    public string CURP { get; set; }

    public string RFC { get; set; }

    public string Telefono { get; set; }

    public string Celular { get; set; }

    public string Email { get; set; }

    public string Genero { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public int IdUsuarioAlta { get; set; }

    public DateTime FechaAlta { get; set; }

    public int? IdUsuarioModifica { get; set; }

    public DateTime? FechaModifica { get; set; }

    public int? IdUsuarioElimina { get; set; }

    public DateTime? FechaElimina { get; set; }

    public virtual ICollection<Usuarios> Usuarios { get; set; } = new List<Usuarios>();
}