// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Proveedores
{
    public int IdProveedor { get; set; }

    public int IdEntidad { get; set; }

    public Guid UUID { get; set; }

    public string Folio { get; set; }

    public int IdEstadoProveedor { get; set; }

    public decimal CreditoPesos { get; set; }

    public decimal CreditoDolares { get; set; }

    public int IdRegimenFiscal { get; set; }

    public bool TieneCredito { get; set; }

    public int DiasCredito { get; set; }

    public int DiasGracia { get; set; }

    public decimal SaldoPesos { get; set; }

    public decimal SaldoDolares { get; set; }

    public string Web { get; set; }

    public string Correo { get; set; }

    public string CuentaContable { get; set; }

    public int IdFormaPago { get; set; }
}