// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Sucursales
{
    public int IdSucursal { get; set; }

    public int IdEntidad { get; set; }

    public string CveSucursal { get; set; }

    public string Denominacion { get; set; }

    public int IdUsuarioAlta { get; set; }

    public DateTime FechaAlta { get; set; }

    public int? IdUsuarioModifica { get; set; }

    public DateTime? FechaModifica { get; set; }

    public int? IdUsuarioElimina { get; set; }

    public DateTime? FechaElimina { get; set; }

    public virtual ICollection<Usuarios_Permisos> Usuarios_Permisos { get; set; } = new List<Usuarios_Permisos>();

    public virtual ICollection<Usuarios_Sucursales> Usuarios_Sucursales { get; set; } = new List<Usuarios_Sucursales>();
}