// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Usuarios
{
    public int IdUsuario { get; set; }

    public int IdPersona { get; set; }

    public Guid GuidUsuarioDirectory { get; set; }

    public int IdUsuarioEstado { get; set; }

    public string Username { get; set; }

    public string TwoFactorKey { get; set; }

    public bool NavegarTabsActivo { get; set; }

    public int? IdMenuInicio { get; set; }

    public string DefaultCulture { get; set; }

    public string DefaultTimeZone { get; set; }

    public DateTime? HeartBeat { get; set; }

    public bool Bloqueado { get; set; }

    public int IdUsuarioAlta { get; set; }

    public DateTime FechaAlta { get; set; }

    public virtual ICollection<Entidades_Contactos> Entidades_Contactos { get; set; } = new List<Entidades_Contactos>();

    public virtual Personas IdPersonaNavigation { get; set; }

    public virtual Usuarios_Estados IdUsuarioEstadoNavigation { get; set; }

    public virtual ICollection<Usuarios_Menus> Usuarios_Menus { get; set; } = new List<Usuarios_Menus>();

    public virtual ICollection<Usuarios_Permisos> Usuarios_Permisos { get; set; } = new List<Usuarios_Permisos>();

    public virtual ICollection<Usuarios_Sucursales> Usuarios_Sucursales { get; set; } = new List<Usuarios_Sucursales>();

    public virtual ICollection<Usuarios_Tokens> Usuarios_Tokens { get; set; } = new List<Usuarios_Tokens>();
}