// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Usuarios_Sucursales
{
    public int IdUsuarioSucursal { get; set; }

    public int IdUsuario { get; set; }

    public int? IdSucursal { get; set; }

    public virtual Sucursales IdSucursalNavigation { get; set; }

    public virtual Usuarios IdUsuarioNavigation { get; set; }
}