// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Usuarios_Menus
{
    public int IdUsuarioMenu { get; set; }

    public int IdUsuario { get; set; }

    public int IdMenu { get; set; }

    public virtual Menus IdMenuNavigation { get; set; }

    public virtual Usuarios IdUsuarioNavigation { get; set; }
}