// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Usuarios_Estados
{
    public int IdUsuarioEstado { get; set; }

    public string Estado { get; set; }

    public string EstadoEN { get; set; }

    public bool PuedeAutenticar { get; set; }

    public virtual ICollection<Usuarios> Usuarios { get; set; } = new List<Usuarios>();
}