// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class Usuarios_Tokens
{
    public int IdUsuarioToken { get; set; }

    public int IdUsuario { get; set; }

    public Guid GuidToken { get; set; }

    public bool Activacion { get; set; }

    public DateTime VigenteHasta { get; set; }

    public DateTime? FechaUsado { get; set; }

    public DateTime FechaAlta { get; set; }

    public virtual Usuarios IdUsuarioNavigation { get; set; }
}