// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class vEntidades
{
    public int IdEntidad { get; set; }

    public int IdTipoEntidad { get; set; }

    public string Entidad_Tipo { get; set; }

    public string Rfc { get; set; }

    public string RazonSocial { get; set; }

    public string NombreComercial { get; set; }

    public int? IdTipoRegimenFiscal { get; set; }

    public int IdTipoPersonaSat { get; set; }

    public int? IdEntidadPadre { get; set; }

    public int IdUsuarioAlta { get; set; }

    public DateTime FechaAlta { get; set; }

    public int? IdUsuarioModifica { get; set; }

    public DateTime? FechaModifica { get; set; }

    public int? IdUsuarioElimina { get; set; }

    public DateTime? FechaElimina { get; set; }
}