// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class vUsuariosPersonas
{
    public int IdUsuario { get; set; }

    public Guid GuidUsuarioDirectory { get; set; }

    public int IdUsuarioEstado { get; set; }

    public string UsuarioEstado { get; set; }

    public string UsuarioEstadoEN { get; set; }

    public bool UsuarioPuedeAutenticar { get; set; }

    public string Username { get; set; }

    public string TwoFactorKey { get; set; }

    public bool NavegarTabsActivo { get; set; }

    public int? IdMenuInicio { get; set; }

    public string DefaultCulture { get; set; }

    public string DefaultTimeZone { get; set; }

    public DateTime? HeartBeat { get; set; }

    public bool Bloqueado { get; set; }

    public int IdUsuarioAlta { get; set; }

    public DateTime FechaAlta { get; set; }

    public int IdPersona { get; set; }

    public string Nombres { get; set; }

    public string PrimerApellido { get; set; }

    public string SegundoApellido { get; set; }

    public string NombreCompleto { get; set; }

    public string CURP { get; set; }

    public string RFC { get; set; }

    public string Telefono { get; set; }

    public string Celular { get; set; }

    public string Email { get; set; }

    public string Genero { get; set; }

    public DateOnly? FechaNacimiento { get; set; }
}