// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class vUsuariosPermisos
{
    public int IdUsuarioPermiso { get; set; }

    public int IdPermiso { get; set; }

    public int? IdMenu { get; set; }

    public int IdUsuario { get; set; }

    public int? IdSucursal { get; set; }

    public string Sucursal { get; set; }

    public string Alias { get; set; }

    public string Descripcion { get; set; }

    public string DescripcionEN { get; set; }

    public string Endpoint { get; set; }

    public string WebMethod { get; set; }

    public bool IsRole { get; set; }

    public int? IdFormulario { get; set; }

    public string ComponentNamespace { get; set; }

    public string ComponentTypeName { get; set; }

    public int? IdModulo { get; set; }
}