// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.Core;

public partial class vUsuariosSucursales
{
    public int IdUsuarioSucursal { get; set; }

    public int IdUsuario { get; set; }

    public int? IdSucursal { get; set; }

    public string CveSucursal { get; set; }

    public string Denominacion { get; set; }

    public int? IdEntidad { get; set; }

    public string Rfc { get; set; }

    public string RazonSocial { get; set; }

    public string NombreComercial { get; set; }
}