// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Cat_Estatus
{
    public int Id_Estatus { get; set; }

    public string Resource_Key { get; set; }

    public string Nombre_ES { get; set; }

    public bool Habilitado { get; set; }
}