// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Catalogo_Insumos_Unidades
{
    public int ID { get; set; }

    public string Name { get; set; }

    public bool Habilitado { get; set; }
}