// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Catalogos
{
    public int ID { get; set; }

    public string Descripcion { get; set; }

    public int Id_Grupo { get; set; }

    public int? Id_SubGrupo { get; set; }

    public string Valor { get; set; }
}