// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Contratistas
{
    public int Id_Contratista { get; set; }

    public int Id_Persona { get; set; }

    public bool Habilitado { get; set; }
}