// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Egresos
{
    public int Id_Egreso { get; set; }

    public int Id_Usuario { get; set; }

    public string Folio { get; set; }

    public DateTime Fecha { get; set; }

    /// <summary>
    /// D=Destajo, G=Gasto
    /// </summary>
    public string Tipo { get; set; }
}