// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Egresos_Partidas
{
    public int Id_Egreso_Partida { get; set; }

    public int Id_Egreso { get; set; }

    public int Id_Obra { get; set; }

    public int Id_Agrupador { get; set; }

    public int Id_Tipo_Trabajo { get; set; }

    public string Decsripcion { get; set; }

    public decimal Monto { get; set; }

    public Guid? UUID_Archivo { get; set; }

    public string Nota { get; set; }

    public int Id_Estatus { get; set; }

    public DateTime? Fecha_Revision { get; set; }
}