// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Empleados
{
    public int IdEmpleado { get; set; }

    public int IdPersona { get; set; }

    public bool Habilitado { get; set; }
}