// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Fraccionamientos_Etapas
{
    public int Id_Fraccionamiento_Etapa { get; set; }

    public int Id_Fraccionamiento { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int Secuencia { get; set; }

    public bool Habilitado { get; set; }
}