// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Fraccionamientos_Etapas_Manzanas
{
    public int Id_Fraccionamiento_Etapa_Manzana { get; set; }

    public int Id_Fraccionamiento { get; set; }

    public int Id_Fraccionamiento_Etapa { get; set; }

    public string Nombre { get; set; }

    public bool Habilitado { get; set; }

    public DateTime Fecha_Alta { get; set; }

    public int Id_Usuario_Alta { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public int? Id_Usuario_Modificacion { get; set; }
}