// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Fraccionamientos
{
    public int Id_Fraccionamiento { get; set; }

    public string Nombre { get; set; }

    public int CodigoPostal { get; set; }

    public bool Habilitado { get; set; }

    public DateTime Fecha_Alta { get; set; }

    public int Id_Usuario_Alta { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public int? Id_Usuario_Modificacion { get; set; }

    public string Logotipo { get; set; }

    public int Id_Sucursal { get; set; }

    public Guid UUID { get; set; }

    public string Folio { get; set; }
}