// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Lotes_Propietarios
{
    public int Id_Lote_Propietario { get; set; }

    public int Id_Lote { get; set; }

    public int Id_Propietario { get; set; }

    public int Id_Tipo { get; set; }

    public DateTime Fecha_Inicio { get; set; }

    public DateTime? Fecha_Fin { get; set; }

    public double? Porcentaje { get; set; }
}