// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Lotes
{
    public int Id_Lote { get; set; }

    public int Id_Fraccionamiento { get; set; }

    public int Id_Etapa { get; set; }

    public int Id_Manzana { get; set; }

    public int Numero_Lote { get; set; }

    public int? Id_Domicilio { get; set; }

    public double Superficia { get; set; }

    public string Vista { get; set; }

    public string Amenidades { get; set; }

    public decimal? Precio_Metro { get; set; }

    public double Frente { get; set; }

    public double Fondo { get; set; }

    public int Id_Uso { get; set; }

    public int Id_Estado { get; set; }

    public int Id_Modelo { get; set; }

    public string Clave_Catastral { get; set; }

    public string DTU { get; set; }

    public decimal? Valor_Total_Inmueble { get; set; }

    public decimal? Valor_Terreno { get; set; }

    public decimal? Valor_Escrituracion { get; set; }

    public double? DTU_Porcentaje { get; set; }

    public decimal? Avaluo { get; set; }

    public int? Id_Estatus_Avaluo { get; set; }

    public string Alineamiento { get; set; }

    public string Licencia_Construccion { get; set; }

    public string Registro_Obra { get; set; }

    public string Terminacion_Obra { get; set; }

    public string Escritura { get; set; }

    public DateTime? Fecha_Escrituracion { get; set; }

    public int? Notario { get; set; }

    public DateTime Fecha_Alta { get; set; }

    public int Id_Usuario_Alta { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public int? Id_Usuario_Modificacion { get; set; }

    public string Poligono_GPS { get; set; }

    public Guid UUID { get; set; }

    public string Folio { get; set; }

    public bool Habilitado { get; set; }

    public virtual ICollection<ReportesDestajos_Partidas_Lotes> ReportesDestajos_Partidas_Lotes { get; set; } = new List<ReportesDestajos_Partidas_Lotes>();
}