// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Modelos
{
    public int ID_Modelo { get; set; }

    public Guid UUID { get; set; }

    public string Folio { get; set; }

    public string Nombre { get; set; }

    public double Metros_Construccion { get; set; }

    public string Descripcion { get; set; }

    public DateTime Fecha_Alta { get; set; }

    public int Id_Usuario_Alta { get; set; }

    public DateTime? Fecha_Modificacion { get; set; }

    public int? Id_Usuario_Modificacion { get; set; }

    public virtual ICollection<Secciones> Secciones { get; set; } = new List<Secciones>();
}