// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Modelos_Precios_Unitarios
{
    public int ID_Modelo_Precio_Unitario { get; set; }

    public int Id_Modelo_Partida { get; set; }

    public string Descripcion { get; set; }

    public int? Secuencia { get; set; }

    public int Habilitado { get; set; }
}