// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Proyectos_Tipos
{
    public int Id_Tipo { get; set; }

    public string Nombre { get; set; }

    public string Icon { get; set; }

    public bool Habilitado { get; set; }
}