// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Relacion_Precios_Unitarios_Insumos
{
    public int ID { get; set; }

    public int Id_Modelo_Precio_Unitario { get; set; }

    public int Id_Insumo { get; set; }

    public int Id_Unidad { get; set; }

    public decimal Volumen { get; set; }

    public decimal Precio { get; set; }

    public bool Habilitado { get; set; }

    public virtual Insumos Id_InsumoNavigation { get; set; }
}