// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class ReportesDestajos
{
    public int IdReporteDestajo { get; set; }

    public int IdReporteDestajoEstatus { get; set; }

    public int IdProyecto { get; set; }

    public int IdSeccion { get; set; }

    public int IdContratista { get; set; }

    public DateOnly FechaReporte { get; set; }

    public string NotasReporte { get; set; }

    public int? IdSupervisor { get; set; }

    public DateOnly? FechasSupervisado { get; set; }

    public int IdUsuarioAlta { get; set; }

    public int? IdUsuarioModifica { get; set; }

    public DateTime FechaAlta { get; set; }

    public DateTime? FechaModifica { get; set; }

    public DateTime? FechaElimina { get; set; }

    public virtual ReportesDestajos_Estatus IdReporteDestajoEstatusNavigation { get; set; }

    public virtual ICollection<ReportesDestajos_Partidas> ReportesDestajos_Partidas { get; set; } = new List<ReportesDestajos_Partidas>();
}