// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class ReportesDestajos_Partidas
{
    public int IdReporteDestajoPartida { get; set; }

    public int IdReporteDestajo { get; set; }

    public int IdModeloPrecioUnitario { get; set; }

    public int PorcentajeReportado { get; set; }

    public int PorcentajeAprobado { get; set; }

    public string NotasContratista { get; set; }

    public string NotasSupervisor { get; set; }

    public DateTime FechaAlta { get; set; }

    public DateTime? FechasSupervisado { get; set; }

    public string Notas { get; set; }

    public virtual ReportesDestajos IdReporteDestajoNavigation { get; set; }

    public virtual ICollection<ReportesDestajos_Partidas_Fotos> ReportesDestajos_Partidas_Fotos { get; set; } = new List<ReportesDestajos_Partidas_Fotos>();
}