// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class ReportesDestajos_Estatus
{
    public int IdReporteDestajoEstatus { get; set; }

    public string Estatus { get; set; }

    public string EstatusEN { get; set; }

    public string GlyphIcon { get; set; }

    public string LightColorHex { get; set; }

    public string DarkColorHex { get; set; }

    public virtual ICollection<ReportesDestajos> ReportesDestajos { get; set; } = new List<ReportesDestajos>();
}