// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class ReportesDestajos_Partidas_Fotos
{
    public int IdReporteDestajoPartidaFoto { get; set; }

    public int IdReporteDestajoPartida { get; set; }

    public int? IdArchivo { get; set; }

    public Guid? TokenUpload { get; set; }

    public DateTime? FechaCaptura { get; set; }

    public DateTime? FechaSincronizacion { get; set; }

    public virtual ReportesDestajos_Partidas IdReporteDestajoPartidaNavigation { get; set; }
}