// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class ReportesDestajos_Partidas_Lotes
{
    public int IdReporteDestajoPartidaLote { get; set; }

    public int IdReporteDestajoPartida { get; set; }

    public int IdLote { get; set; }

    public virtual Lotes IdLoteNavigation { get; set; }
}