// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Secciones_Explosiones_Insumos
{
    public int Id_Seccion_Explosion_Insumos { get; set; }

    public int Id_Proyecto { get; set; }

    public int Id_Seccion { get; set; }

    public decimal Total_Insumos { get; set; }

    public decimal Incremento_Mano_Obra { get; set; }

    public decimal Honorarios { get; set; }

    public decimal Total { get; set; }

    public Guid UUID { get; set; }

    public string Folio { get; set; }
}