// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Secciones_Explosiones_Insumos_Detalle
{
    public int Id_Secciones_Explosiones_Insumos_Detalle { get; set; }

    public int Id_Seccion_Explosion_Insumos { get; set; }

    public int Id_Producto { get; set; }

    public double Cantidad { get; set; }

    public decimal Costo_Unitario { get; set; }

    public decimal Importe { get; set; }
}