// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Secciones_Fases
{
    public int Id_Seccion_Fase { get; set; }

    public int Id_Seccion { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int Secuencia { get; set; }

    public bool Terminada { get; set; }

    public bool Habilitado { get; set; }
}