// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Secciones_Fases_Visitas
{
    public int Id_Seccion_Fase_Visita { get; set; }

    public int Id_Seccion_Fase { get; set; }

    public DateTime Fecha { get; set; }

    public string Notas { get; set; }

    public int Id_Usuario_Alta { get; set; }
}