// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Secciones_Lotes_Modelos_Evidencias
{
    public int Id_Seccion_Lote_Modelo_Evidencia { get; set; }

    public int Id_Seccion_Fase_Evidencia { get; set; }

    public string Foto { get; set; }
}