// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Secciones_Lotes
{
    public int Id_Seccion_Lotes { get; set; }

    public int Id_Seccion { get; set; }

    public int Id_Lote { get; set; }

    public int Id_Modelo { get; set; }

    public bool Habilitado { get; set; }
}