// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Secciones_Modelos_Casas
{
    public int Id_Seccion_Modelo_Casa { get; set; }

    public int Id_Seccion { get; set; }

    public int Id_Modelo { get; set; }

    public int TotalUnidades { get; set; }

    public int NumeroPaquete { get; set; }
}