// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class Sucursales
{
    public int Id_Sucursales { get; set; }

    public string Nombre { get; set; }

    public string RFC { get; set; }

    public int Secuecnia { get; set; }

    public bool Habilitada { get; set; }

    public Guid UUID { get; set; }

    public string Folio { get; set; }
}