// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class vContratistas
{
    public int Id_Contratista { get; set; }

    public string Nombres { get; set; }

    public string PrimerApellido { get; set; }

    public string SegundoApellido { get; set; }

    public string Genero { get; set; }

    public bool Habilitado { get; set; }
}