// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class vEgresos_Detalle
{
    public int Id_Egreso { get; set; }

    public int? IdUsuario { get; set; }

    public int? IdPersona { get; set; }

    public string Usuario { get; set; }

    public string Folio { get; set; }

    public DateTime Fecha { get; set; }

    public string Tipo { get; set; }
}