// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class vInsumos
{
    public int ID { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    public int Id_Tipo { get; set; }

    public string Tipo_Insumo { get; set; }

    public bool Habilitado { get; set; }
}