// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class vInsumos_Modelos
{
    public int ID_Relacion_PU_Insumo { get; set; }

    public int ID_Modelo { get; set; }

    public string Modelo { get; set; }

    public string Partida { get; set; }

    public string Precio_Unitario { get; set; }

    public string Insumo { get; set; }

    public string Unidad { get; set; }

    public string Tipo_Insumo { get; set; }

    public decimal Volumen { get; set; }

    public int? Precio { get; set; }

    public int? Importe { get; set; }
}