// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class vModelosExplosionInsumos
{
    public int ID_Modelo { get; set; }

    public string Modelo { get; set; }

    public int ID_Grupo { get; set; }

    public string Grupo { get; set; }

    public int ID_Partida { get; set; }

    public string Partida { get; set; }

    public int ID_Precio_Unitario { get; set; }

    public string Precio_Unitario { get; set; }

    public int ID_Insumo { get; set; }

    public string Insumo { get; set; }

    public int Id_Tipo { get; set; }

    public string Tipo { get; set; }

    public int ID_Unidad { get; set; }

    public string Unidad { get; set; }

    public decimal Volumen { get; set; }

    public decimal Precio { get; set; }
}