// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class vReportesDestajos_Partidas_Fotos
{
    public int IdReporteDestajoPartidaFoto { get; set; }

    public int IdReporteDestajoPartida { get; set; }

    public Guid? TokenUpload { get; set; }

    public DateTime? FechaCaptura { get; set; }

    public DateTime? FechaSincronizacion { get; set; }

    public int IdArchivo { get; set; }

    public string NombreOriginal { get; set; }

    public string RutaRelativa { get; set; }

    public DateTime FechaAlta { get; set; }

    public int IdArchivoTipo { get; set; }

    public string TipoArchivo { get; set; }

    public string Extension { get; set; }

    public string MimeType { get; set; }
}