// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.ProyectosConstruccion;

public partial class vSecciones_Lotes
{
    public Guid? ProyectoGuid { get; set; }

    public Guid SeccionGuid { get; set; }

    public string Proyecto { get; set; }

    public string Fraccionamiento { get; set; }

    public string Fraccionamiento_Etapa { get; set; }

    public string Manzana { get; set; }

    public int Lote { get; set; }
}