// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Nubetico.DAL.Models.PortalProveedores;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Nubetico.DAL.Models.PortalProveedores
{
    public partial interface IPortalProveedoresContextProcedures
    {
        Task<List<sp_obra_getResult>> sp_obra_getAsync(int? IdObra, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_obra_postAsync(string Nombre, DateTime? FechaInicio, DateTime? FechaFin, int? IdPersonaResidente, int? IdPersonaCoordinador, int? IdEstadoObra, int? IdTipoObra, bool? EsProyectoObra, bool? Completada, string Observaciones, OutputParameter<int?> IdObra, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_obra_putAsync(int? IdObra, string Nombre, DateTime? FechaInicio, DateTime? FechaFin, int? IdPersonaResidente, int? IdPersonaCoordinador, int? IdEstadoObra, int? IdTipoObra, bool? EsProyectoObra, bool? Completada, string Observaciones, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_obras_getResult>> sp_obras_getAsync(string Nombre, int? IdPersonaResidente, int? IdEstadoObra, bool? EsProyectoObra, bool? ObraTerminada, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
