// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Nubetico.DAL.Models.PortalProveedores;

public partial class PortalProveedoresContext : DbContext
{
    public PortalProveedoresContext(DbContextOptions<PortalProveedoresContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Obras> Obras { get; set; }

    public virtual DbSet<vObras> vObras { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Obras>(entity =>
        {
            entity.HasKey(e => e.Id_Obra).HasName("PK_Obras_Id_Obra");

            entity.ToTable("Obras", "nb_pp");

            entity.Property(e => e.Completada).HasDefaultValue(false);
            entity.Property(e => e.Es_Proyecto_Obra).HasDefaultValue(true);
            entity.Property(e => e.Fecha_Fin).HasColumnType("datetime");
            entity.Property(e => e.Fecha_Inicio).HasColumnType("datetime");
            entity.Property(e => e.Nombre).HasMaxLength(250);
            entity.Property(e => e.Observaciones).HasMaxLength(255);
        });

        modelBuilder.Entity<vObras>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vObras", "nb_pp");

            entity.Property(e => e.Estado_Obra).HasMaxLength(50);
            entity.Property(e => e.Fecha_Fin).HasColumnType("datetime");
            entity.Property(e => e.Fecha_Inicio).HasColumnType("datetime");
            entity.Property(e => e.Nombre).HasMaxLength(250);
            entity.Property(e => e.Observaciones).HasMaxLength(255);
            entity.Property(e => e.Residente)
                .IsRequired()
                .HasMaxLength(302);
            entity.Property(e => e.Tipo_Obra).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}