// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nubetico.DAL.Models.PortalProveedores;

public partial class vObras
{
    public int Id_Obra { get; set; }

    public string Nombre { get; set; }

    public DateTime? Fecha_Inicio { get; set; }

    public DateTime? Fecha_Fin { get; set; }

    public int? Id_Persona_Residente { get; set; }

    public string Residente { get; set; }

    public int? Id_Estado_Obra { get; set; }

    public string Estado_Obra { get; set; }

    public int? Id_Persona_Coordinador { get; set; }

    public int? Id_Tipo_Obra { get; set; }

    public string Tipo_Obra { get; set; }

    public bool? Es_Proyecto_Obra { get; set; }

    public bool? Completada { get; set; }

    public string Observaciones { get; set; }
}